In [8]:
class Employee:#Class for Employee objects
    employeeCount=0 #To count number of employee objects
    salarySum=0 #sum of salaries to find average of the sum 
    def __init__(self,name,family,salary,department): #constructor for Employee as per the requirements
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employeeCount += 1
        Employee.salarySum+=self.salary
    def avg(self):
        return Employee.salarySum/Employee.employeeCount
    def displayEmployee(self):
        print("Name :", self.name, ", Family:", self.family , ", Salary:", self.salary, ", Department:",self.department)

emp1 = Employee("Abrar Pasha","Mohammed",40000,"Computer Science")#Employee objects creation with intialization
emp2 = Employee("Azeem Pasha","Mohammed",50000,"Electronics")
print("avg:",emp2.avg())#calling Average function

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

fte=FulltimeEmployee("Shahista","Farheen",90000,"Medic")#FultimeEmployee object
fte.displayEmployee()

avg: 45000.0
Name : Shahista , Family: Farheen , Salary: 90000 , Department: Medic


In [9]:
import numpy as np #importing the numpy library
vector=np.arange(1,21,dtype=float)
print(vector)
vector=vector.reshape(4,5)
print(vector)
vector=np.where(np.isin(vector,vector.max(axis=1)),0,vector)
vector

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


array([[ 1.,  2.,  3.,  4.,  0.],
       [ 6.,  7.,  8.,  9.,  0.],
       [11., 12., 13., 14.,  0.],
       [16., 17., 18., 19.,  0.],
       [21., 22., 23., 24.,  0.]])